### ISSUE TITLE
Newlines at end of prompt

### ISSUE THREAD

**Issue by mschubert** [randy3k/rtichoke#39]
There always seem to be 5 newlines at the end of the prompt.

Is there a way to use all lines available in the terminal?

**Comment by randy3k** [comment]
The lines are reserved for completions. You could turn off the setting `rtichoke.complete_while_typing` (check README for details)

**Comment by mschubert** [comment]
That makes sense, thank you for you answer.

Nevertheless, I don't think this is a good solution: it's wasting vertical space, and when you use vertical splits for Nvim+R, then this quickly becomes a nuisance.

Would it be possible to use the available space for completions instead of always using the lines after the prompt?

I'm thinking along the lines how `YouCompleteMe` does it:

![](https://image.ibb.co/mVRmoH/Screenshot_from_2018_02_24_23_47_53.png)

**Comment by randy3k** [comment]
The way that the completion works depends on `prompt-toolkit`, which is the library rtichoke uses under the hood. It may be possible to change the display layout if one dive deep into their codebase.

**Comment by randy3k** [comment]
Also, there are almost certainly completion items to display if `complete_while_typing` is true. Reserving some spaces is actually the way to go.
