### ISSUE TITLE
Cannot type after sending text to console

### ISSUE THREAD

**Issue by MilesMcBain** [randy3k/rtichoke#40]
This is a strange one that only started after I switched from `rice` to `rtichoke` on the weekend. I've replicated the same behaviour on two separate machines (both Ubuntu), in VSCode and RStudio. If I send R code from an editor pane to a terminal running `rtichoke` in either program, the code executes fine, but after this the program enters a bugged state where I can no longer view text typed directly into `rtichoke`.

In this state, when I make keystrokes the cursor stays stuck immediately after the prompt. However if I press 'enter', `rtichoke` will run whatever I typed and produce output. So it is receiving input, just not displaying anything. I haven't found any way to recover from this state.

If I start `rtichoke` in a terminal and do not send code to it from an editor pane, it works normally.

Edit: I've tested if preloadeding any dynamic libs, as discussed in out thread, is the cause. It does not appear to be.

**Comment by randy3k** [comment]
Thanks for the report. Does the size of the R code sent matter?

**Comment by MilesMcBain** [comment]
I've tried single lines and a few 'paragraphs' it's happening reliably with any amount.

**Comment by randy3k** [comment]
Let me take a look later today.

**Comment by randy3k** [comment]
I cannot reproduce it on my ubuntu / rstudio. How did you send the code to RStudio?

![feb-26-2018 07-32-05](https://user-images.githubusercontent.com/1690993/36670770-4412a57e-1ac7-11e8-924d-a0c075751fe3.gif)

**Comment by MilesMcBain** [comment]
I use Crtl + enter, which works as you have shown.

I am sorry if my explanation was unclear. What does not work is if I try to type at the `r$>` prompt in the terminal after I have sent text there. So in your gif you would need to place the cursor in the terminal and try typing at the new prompt after the `b <-  2` is sent.

**Comment by randy3k** [comment]
Great. I can reproduce it now.

**Comment by randy3k** [comment]
It was a bug introduced when fixing #35 
1bb76a45629db8aeef26ee0366341e5be480d2f3 should fix this.

v0.1.2 is just released.

**Comment by MilesMcBain** [comment]
Awesome, it's back to working great! PS I wrote a little bit about `rtichoke` and the R language server on my new blog: https://milesmcbain.xyz/alt-r-with-vscode/ Keep up the great work!
