### ISSUE TITLE
Auto completion is laggy

### ISSUE THREAD

**Issue by beansrowning** [randy3k/rtichoke#42]
This may just be due to the number of packages I have installed, but using R interactively with rtichoke is quite laggy at the moment. It takes 4-5 seconds to search for completions as I type out a function name. 

I'm not sure how indexing is being accomplished currently, but maybe searching only attached packages or individual namespaces when "package::xx" is entered would be more efficient if it's not already being done.

This is an awesome concept though. I admire all of your hard work!

**Comment by randy3k** [comment]
What version of R are you using? I recall that 3.4.2 used to be slow. Upgrading 3.4.3 fixed the slowness for me.

**Comment by beansrowning** [comment]
Good suggestion. I use 3.4.2 and 3.4.1, so I will have to test a later version and check back.

**Comment by beansrowning** [comment]
@randy3k 
Sorry for the late response--I work for a corporation with tighter restrictions for updating R versions.

I've now tried with later versions and it seems like the slowness is fixed at least a little bit. I'll go ahead and close it for now unless someone else reports it as well.

**Comment by randy3k** [comment]
rtichoke 0.1.8 is out, it checks if a completion is taking too long and would cancel if necessary.
