### ISSUE TITLE
Proper table printing broken with R 3.5

### ISSUE THREAD

**Issue by beansrowning** [randy3k/rtichoke#50]
### Setup:  
- R 3.5.0  
- rtichoke 0.1.2  
- Windows 10  
- ConEmu  

### Reproducible example:
```r
data.frame(a = 1:2, x = c("a", "b"))
#> ☻ÿþa♥ÿþ ☻ÿþx♥ÿþ
#> ☻ÿþ1♥ÿþ ☻ÿþ1♥ÿþ ☻ÿþa♥ÿþ
#> ☻ÿþ2♥ÿþ ☻ÿþ2♥ÿþ ☻ÿþb♥ÿþ
```

**Comment by randy3k** [comment]
For the record, it works fine on macOS.

**Comment by beansrowning** [comment]
Data.table looks to be affected too:
```r
data.table(a = 1:2, x = c("a", "b"))
#>  ☻ÿþa♥ÿþ ☻ÿþx♥ÿþ
#>☻ÿþ1:♥ÿþ ☻ÿþ1♥ÿþ ☻ÿþa♥ÿþ
#>☻ÿþ2:♥ÿþ ☻ÿþ2♥ÿþ ☻ÿþb♥ÿþ
```  

Not tibbles though:  
```r
tibble(a = 1:2, x = c("a", "b"))
#> # A tibble: 2 x 2
#>       a x
#>   <int> <chr>
#>  1     1 a
#>  2     2 b

```

**Comment by randy3k** [comment]
It works fine both on Cmder and Command Prompt.

![screen shot 2018-04-26 at 5 16 27 pm](https://user-images.githubusercontent.com/1690993/39332491-93d362f6-4975-11e8-8443-f066c594d21c.png)

**Comment by beansrowning** [comment]
It looks like your R version is 3.4.3. Here's what I'm getting with 3.5:  
![capture2](https://user-images.githubusercontent.com/25888380/39332577-e383bc24-4975-11e8-8808-ebc4b71a3d64.PNG)

![capture](https://user-images.githubusercontent.com/25888380/39332581-e59a3ba0-4975-11e8-965c-9716f0e7bd6e.PNG)

**Comment by randy3k** [comment]
Oh, yeah. I can reproduce it via R 3.5.

**Comment by beansrowning** [comment]
Yeah regular R works fine--I'm using cmder as well FWIW.  

I dug around a bit in the R repo and didn't see any major changes to printing, nor was there anything in the release notes. Very odd.

**Comment by randy3k** [comment]
More odd,

```
r$> list(a = 1, b = 2)
$`☻ÿþa♥ÿþ`
[1] 1

$b
[1] 2
```

**Comment by randy3k** [comment]
for some reason, `"a"` is printed as `"\x02\xff\xfea\x03\xff\xfe"` with the extra escaped characters.

**Comment by beansrowning** [comment]
That is just odd...what has changed do you think?

**Comment by randy3k** [comment]
I notice that [rstudio](https://github.com/rstudio/rstudio/blob/bcff365171306a977030d3332f145dd7f92117bb/src/cpp/r/RUtil.cpp#L88) has code related to these escaped characters.

**Comment by beansrowning** [comment]
The relevant [commit](https://github.com/rstudio/rstudio/commit/b6d47e7b6c229e2989d8193a30f1b8ce9ec89a2a) from Joe Cheng, if you didn't see that already. Looks like R output needs to be homogenized to utf-8.

**Comment by randy3k** [comment]
4e29747 should fix it.

**Comment by Hong-Revo** [comment]
I don't know if this helps, but `0xFEFF` is the UTF-16 encoding of the [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark).

**Comment by beansrowning** [comment]
@randy3k Confirmed working on Command Prompt and Cmder with the most recent version. Nice work!

**Comment by randy3k** [comment]
But I still what happens to R 3.5 is causing this.
