### ISSUE TITLE
rJava package not loading

### ISSUE THREAD

**Issue by chrisoswald** [randy3k/rtichoke#54]
Hello,
with rtichoke I cannot load rJava and/or dependent packages. I get always an error

`Error: package or namespace load failed for ‘rJava’:
 .onLoad in loadNamespace() für 'rJava' fehlgeschlagen, Details:
  Aufruf: dyn.load(file, DLLpath = DLLpath, ...)
  Fehler: kann shared object '../R/x86_64-pc-linux-gnu-library/3.4/rJava/libs/rJava.so' nicht laden:
  libjvm.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
`
But the rJava.so file is at the given location. 

Any ideas?

Thanks,
Christian

Linuxmint 18.3,
R 3.4, 
java-1.8.0-openjdk-amd64 
rjava: 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11"

**Comment by randy3k** [comment]
What version of rtichoke are you using?

**Comment by chrisoswald** [comment]
I have tested the development version also

rtichoke version: 0.2.0
r executable: /usr/lib/R/bin/R
r version: 3.4.4
python executable: /usr/bin/python
python version: 2.7.12

The same result:
Fehler: package or namespace load failed for ‘rJava’:
 .onLoad in loadNamespace() für 'rJava' fehlgeschlagen, Details:
  Aufruf: dyn.load(file, DLLpath = DLLpath, ...)
  Fehler: kann shared object '/home/cosw/R/x86_64-pc-linux-gnu-library/3.4/rJava/libs/rJava.so' nicht laden:
  libjvm.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

**Comment by randy3k** [comment]
I guess you just need to expose the path to `libjvm.so` to the variable `R_LD_LIBRARY_PATH `.

**Comment by chrisoswald** [comment]
you are right, it's working now.
Thanks.

**Comment by randy3k** [comment]
Awesome
