### ISSUE TITLE
libR.so

### ISSUE THREAD

**Issue by deto** [randy3k/rtichoke#58]
I was trying to get rtichoke to work today and having trouble - it could not find the shared library.  My path was set up correctly so that it found the R installation directory, but I just didn't have a libR.so

Eventually, after some googling, I found that the issue is I compiled R from source and didn't enable the compilation flag "--enable-R-shlib".  Apparently, with out this, you don't get a libR.so file.

I'll probably recompile sometime soon so I can start using rtichoke (because it looks awesome), but I was thinking it may be useful to include this info in the FAQ or as part of the error message to save other people some time who might have the same issue.

**Comment by randy3k** [comment]
You are right. It requires R to be compiled with the flag `--enable-R-shlib` so that it prepares the shared library `libR.so`. It would be great if you could tell me the error that you encountered.

**Comment by deto** [comment]
The specific place it error'd was actually inside the rapi codebase:

https://github.com/randy3k/rapi/blob/e5819e5dc8d75d296b25553a5d2e0241c3dfe823/rapi/utils.py#L71

And I was running Ubuntu 16.04
