### ISSUE TITLE
"--restore-data" is an unknown option for R

### ISSUE THREAD

**Issue by ashawkey** [randy3k/rtichoke#59]
Since there isn't a "--restore-data" option for original R, I think you shouldn't add this option [here (line 154)](https://github.com/randy3k/rtichoke/blob/master/rtichoke/rtichokeapp.py).

(After all, it just leads to a warning if I start rtichoke with this option. It works well and will restore previous data : )

**Comment by randy3k** [comment]
You are right. We should set `--no-restore-data` as part of the argument if `--restore-data` is not passed to rtichoke.

**Comment by randy3k** [comment]
fix in 7017b002a3e4a8da6c435d6b01f3ba04f2655473
