### ISSUE TITLE
option to silence greeting?

### ISSUE THREAD

**Issue by t-kalinowski** [randy3k/rtichoke#61]
Hi,

I've been playing around with rtichoke lately. It's a nice piece of software! 

Would it be possible to silence the greeting?
[this line](https://github.com/randy3k/rtichoke/blob/master/rtichoke/rtichokeapp.py#L181) perhaps controllabe by a flag added [here](https://github.com/randy3k/rtichoke/blob/master/rtichoke/__init__.py#L23)

Maybe adding a "--quiet" command line argument to rtichoke, to match R's flag?

**Comment by randy3k** [comment]
Checkout the development version and here you are.~

**Comment by t-kalinowski** [comment]
Awesome! Thank you!
