### ISSUE TITLE
import error- no module named queue

### ISSUE THREAD

**Issue by scm-unimelb** [randy3k/rtichoke#62]
just installed rtichoke on Mac High Sierra wih defasult python 2.7, and getting a stack trace which ends with this error. Is there anything obvious we should be checking for? Thank you, Steve

**Comment by randy3k** [comment]
Could you report the whole stack trace error?

**Comment by randy3k** [comment]
It seems to be the version of six is too old. Try
```
pip install -U six
```

I will make a lower bound of the version of six.

**Comment by scm-unimelb** [comment]
thank you, yes - six is the last package in the trace. Currently at v 1.4.1. 
The straight install failed 
'Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.' 
The owner and computer is travelling overseas at the moment, but I will report back after we have tried 'pip install -U --ignore-installed six'..

**Comment by randy3k** [comment]
I believe you could install it to your user directory by passing the argument `--user`.

**Comment by scm-unimelb** [comment]
This seems related to the final transition to the TLS 1.2 protocol for pip. I was not able to update rtichoke on my own Mac yesterday. I installed Python 3.7 from https://www.python.org/downloads/, and then >python3 -m pip install --upgrade pip brought me up to v 18. No problems updating rtichoke  since. I just needed a restart for the new rtichoke to appear in my PATH.
