### ISSUE TITLE
View(df) function error in Windows 10

### ISSUE THREAD

**Issue by demillan** [randy3k/rtichoke#64]
Hi, I get an error when I try to execute the following code in VSCode integrated terminal:

`View(iris)`

The error is the same no matter I execute it in CMD or in the integrated terminal within VSCode.

This was tried running R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree" in Windows 10.

But if I try:

`plot(iris)`

And then:

`View(iris)`

It works.

Error message:

`Traceback (most recent call last):
  File "c:\users\user\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\Scripts\rtichoke.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\rtichoke\__init__.py", line 72, in main
    RtichokeApplication(r_home, ver=__version__).run(options)
  File "c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\rtichoke\rtichokeapp.py", line 184, in run
    m.run_loop()
  File "c:\users\user\appdata\local\continuum\anaconda3\lib\site-packages\rapi\bootstrap.py", line 268, in run_loop
    self.libR.run_Rmainloop()
OSError: exception: access violation reading 0x000000000000015C`

**Comment by randy3k** [comment]
I didn’t expect the `View` function to work at all. What surprising is that it works after plotting. Thanks for the report. I’ll need to set up the data viewer correctly (which I know it wasn’t)

**Comment by randy3k** [comment]
It is fixed with current master of rapi https://github.com/randy3k/rapi.

A release of rtichoke will be published soon.

**Comment by randy3k** [comment]
v0.2.9 is released.

**Comment by StevenLi-DS** [comment]
I'm using `radian 0.4.4`, but neither of `View()` nor `plot()` work at all. Not window show up. Am I missing something?
![image](https://user-images.githubusercontent.com/33796896/72673628-59112a00-3a3b-11ea-84d5-659c2972eac3.png)

**Comment by randy3k** [comment]
That's odd. By the way, how did you get it working at this [screenshot](https://github.com/Ikuyadeu/vscode-R/issues/190#issuecomment-574993049)?

**Comment by StevenLi-DS** [comment]
@randy3k It doesn't work in this screenshot. `plot()` and `View()` only work if I double-click the R.exe at the folder `C:\Program Files\R\R-3.6.1\bin\x64` and use that terminal.

**Comment by randy3k** [comment]
I believe that the screenshot was showing the radian prompt.

**Comment by StevenLi-DS** [comment]
> I believe that the screenshot was showing the radian prompt.

I launch cmd and then type `radian` to have the screenshot

**Comment by randy3k** [comment]
Let me see if I understand correctly, did you mean that `View(mtcars)` works if you launch `radian` from `CMD.exe`, but it doesn't work if you launch `radian` inside VSCode?

**Comment by StevenLi-DS** [comment]
Now `radian` works as long as I don't add `C:\Program Files\R\R-3.6.1\bin\x64` into my PATH variable

**Comment by randy3k** [comment]
Do you have multiple copies of R? Check `radian --version`.

**Comment by StevenLi-DS** [comment]
I got
```
radian version: 0.4.4
r executable: C:\Users\liqia\Anaconda3\lib\R\bin\R
r version: 3.6.1
python executable: c:\users\liqia\anaconda3\python.exe
python version: 3.7.3
```

**Comment by randy3k** [comment]
So you have two copies of R, one copy in `C:\Program Files\R\R-3.6.1` and another copy in `C:\Users\liqia\Anaconda3\lib\R`.

For some reason, the copy of R in `C:\Program Files\R\R-3.6.1` is not working properly.

**Comment by StevenLi-DS** [comment]
Indeed, 
I just added `C:\Program Files\R\R-3.6.1\bin\x64` and moved it to the top. and then `View()` no longer works. It seems like adding path variable causes the issue.
