### ISSUE TITLE
Possible to start with a different process name 

### ISSUE THREAD

**Issue by saptarshiguha** [randy3k/rtichoke#65]
Hello,
I'm using tmux to programmatically send commands to the rtichoke console. However when I run

```
 tmux list-panes  -F  '#{pane_id} #{pane_current_command} '
```

the command is `python3.4` making it difficult to distinguish this pane from other python panes. Is it possible to put rtichoke into the process name?

**Comment by randy3k** [comment]
Oh. I only tested on my mac and it worked. However, it doesn't seem to work on ubuntu...

**Comment by saptarshiguha** [comment]
Thanks much I’ll test on Centos and get back to you

**Comment by saptarshiguha** [comment]
Just wanted to say this works as expected on centos. Thanks much! Really nice program.
