### ISSUE TITLE
typing `source("...")` for the first time causes a long pause

### ISSUE THREAD

**Issue by saptarshiguha** [randy3k/rtichoke#66]
Hello
When i start to type `source` by the third letter there is a long pause and then everything is back to normal.

Do you know why?
thanks much

**Comment by randy3k** [comment]
R is caching a list of completions at that time. If it really annoys you, you could turn off the auto completion while typing.

**Comment by saptarshiguha** [comment]
It's quite long, say 2 seconds? See this video:

https://www.youtube.com/watch?v=Vt-VlI0C05o

Note the pause is not my having stopped typing, i continued writing
source("~/prefix.R") but the input stopped.

**Comment by randy3k** [comment]
That's strange. I didn't expect a delay so long. Maybe it is a particular slow/buzy machine?
Also, I expect the timeout would kick in after 0.05 second. So either the timeout function is taking a considerable amount of time to cancel the autocompletion or it fails to cancel the autocompletion.

It is what I get.
![aug-31-2018 00-47-31](https://user-images.githubusercontent.com/1690993/44893172-8d097500-acb7-11e8-924d-83441ba646db.gif)

**Comment by saptarshiguha** [comment]
Hmm I think I know. The system is not slow but the file system is an ec2
ebfs backed system. There might be some slow network effects happening.

Not much I can change on my end.

Thanks much I’ll close this issue
