### ISSUE TITLE
Help pages don't work after devtools::load_all

### ISSUE THREAD

**Issue by adibender** [randy3k/rtichoke#68]
Opening help pages usually works, however, after loading a package with 
`devtools::load_all()` I get this error: 

```
Error in file(con, "r") : cannot open the connection                                
In addition: Warning message:                                                       
In file(con, "r") :                                                                 
  cannot open file '/usr/lib/R/share/Rd/macros/system.Rd': No such file or directory
```

**Comment by adibender** [comment]
Hm, don't think so. Tried with different projects, same problem.

**Comment by randy3k** [comment]
Could you provide some reproducible steps?

**Comment by adibender** [comment]
it appears the problem is independent of rtichoke as the problem also occurs in standard R console.
