### ISSUE TITLE
installing fine with pip install -U rtichoke - but then running "rtichoke" says "command not found"

### ISSUE THREAD

**Issue by emilBeBri** [randy3k/rtichoke#73]
Pretty much what the title says.  it installs fine with

`pip install -U rtichoke` 

- but then running "rtichoke" from a terminal gives me the error  "command not found".

I just installed Lubuntu 18.10, rtichoke worked fine with the normal install on my Lubuntu 18.04 installation.

Thank you for your time.

**Comment by randy3k** [comment]
Maybe this post will help

stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

**Comment by emilBeBri** [comment]
oh shoot I knew I had seen it before.. faulty memory, sorry :(
